// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN78nGT2Z1tWvebdfaIOkd192jvQMx8fM',
    appId: '1:964960934583:web:935986a502e70309bb4b32',
    messagingSenderId: '964960934583',
    projectId: 'db-gestion-alimentos',
    authDomain: 'db-gestion-alimentos.firebaseapp.com',
    storageBucket: 'db-gestion-alimentos.appspot.com',
    measurementId: 'G-8L5KG4JTYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9ls0e7LevdLSLw0fnC6bMFb8aIwT-4s',
    appId: '1:964960934583:android:078a1d529b271114bb4b32',
    messagingSenderId: '964960934583',
    projectId: 'db-gestion-alimentos',
    storageBucket: 'db-gestion-alimentos.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN78nGT2Z1tWvebdfaIOkd192jvQMx8fM',
    appId: '1:964960934583:web:07355106f5ed541dbb4b32',
    messagingSenderId: '964960934583',
    projectId: 'db-gestion-alimentos',
    authDomain: 'db-gestion-alimentos.firebaseapp.com',
    storageBucket: 'db-gestion-alimentos.appspot.com',
    measurementId: 'G-S5ST66MM48',
  );
}
